Added show file support and command line flags

diff --git a/squash b/squash
--- a/squash
+++ b/squash
@@ -1,52 +1,55 @@
 #!/usr/bin/env bash
 #
-# -- squash : simple bash script to apply color themes to unix systems
-# -- Author : Joshua L Ervin @ University of Washington
-# -- Contact: jlervin@posteo.net 
+# squash - simple bash script to manage and apply
+#          colors on unix systems
+#
+# written by Joshua Ervin
+# jlervin@posteo.net
 
-COLOR_SCHEME="${1}"
-SQUASH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CACHE_DIR="${HOME}/.cache/squash"
+THEME_DIR="${HOME}/.config/squash/themes"
 NEWLINE=$'\n'
 
-source "${SQUASH_DIR}/defaults"
-
-function usage() 
+usage()
 {
-    printf "Usage: squash <THEME_NAME>\n"
-    printf "Example: squash designr\n"
-    printf "         squash -b -w designr\n"
-    printf "\n"
-    exit 1
+printf "%s" "\
+Usage: squash [-h] [-c /path/to/config/file]
+              [-b] [-n] [-w] [-t] [-l]
+              [-w] [-d] [-f]
+              [-e /path/to/external/script]
+              [/path/to/file]
+
+Example: squash gruvbox
+         squash -n agila
+
+Flags:
+  -h    display this message
+  -c    configuration file location
+  -b    don't reload bar
+  -n    dont't reload nvim
+  -w    don't change wallpaper
+  -t    don't reload terminals
+  -m    don't reload windowmanager 
+  -d    don't reload dunst 
+  -f    don't write files
+  -e    run script after squash
+  -l    list all available themes
+"
+exit 0
 }
 
-test -z "${1}" && usage
-
-if [[ ! -f ${THEME_DIR}/${COLOR_SCHEME} ]]; then
-    printf "Error: Colorscheme not found\n"
-    printf "Exiting program\n"
-    exit 0
-fi
-
-# Source necessary squash files
-#source "${SQUASH_DIR}/defaults"
-source "${THEME_DIR}/${COLOR_SCHEME}"
-
-color_array=($BLK $RED $GRN $YLW $BLU $MAG $CYN $WHT \
-             $BBLK $BRED $BGRN $BYLW $BBLU $BMAG $BCYN $BWHT)
-
-# Uses the sourced color array to create a sequence
-# of escape codes for x terminals, and update their
-# colors without restarting them
-function update_terminals() 
+update_terminals() 
 {
     local sequence=""
 
     for i in {0..15}; do 
-        sequence+="\033]4;${i};${color_array[${i}]}\007"
+        sequence+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
     done
+
     for i in 10 12 13; do 
         sequence+="\033]${i};${FG}\007"
     done
+
     for i in 11 14 708; do 
         sequence+="\033]${i};${BG}\007"
     done
@@ -60,12 +63,7 @@ function update_terminals()
     reload_terminals "${sequence}"
 }
 
-# Identifies the current window manager 
-# and reloads the given window manager using the
-# given colors. 
-# Notes:
-#   Requires wmctrl to identify window manager
-function update_wm() 
+update_wm() 
 {
     if [[ ! $(command -v wmctrl) ]]; then
         printf "Error: cmtrl not found, wm will not be reloaded\n"
@@ -81,16 +79,14 @@ function update_wm()
             $"windowchef")
                 reload_chef
             ;;
+            $"i3")
+                reload_i3
+            ;;
         esac
     fi
 }
 
-# Updates neovim by overwriting the current colorscheme in the .vimrc
-# and sending remote commands to source $MYVIMRC to all vim instances
-# Notes:
-#   Requires neovim-remote to function
-#   Will overwrite the current theme in you .vimrc 
-function update_nvim()
+update_nvim()
 {
     if [[ -z ${VIM_SCHEME} ]]; then
         printf "Error: VIM_SCHEME not set: not changing vim colorscheme\n"
@@ -100,9 +96,7 @@ function update_nvim()
     fi
 }
 
-# Kills all current instances of lemonbar and starts the current bar in the background
-# Notes:
-function update_bar() 
+update_bar() 
 {
     if [[ $(pgrep lemonbar) ]]; then
         pkill -x lemonbar
@@ -112,16 +106,29 @@ function update_bar()
     ( ${BAR_SCRIPT} &) > /dev/null 2>&1
 }
 
-function update_wall()
+update_wall()
 {
     if [[ -z ${WALLPAPER_PATH} ]]; then
         printf "Error: WALLPAPER_PATH not set: not changing wallpaper\n"
-    else
+    elif [[ $(command -v hsetroot) ]]; then
         hsetroot -"${WALLPAPER_STYLE}" "${WALLPAPER_PATH}"
+    elif [[ $(command -v feh) ]]; then
+        if [[ ${WALLPAPER_STYLE} == "tile" ]]; then
+            feh --bg-fill "${WALLAPPER_PATH}"
+        else
+            feh --bg-tile "${WALLPAPER_PATH}"
+        fi
+
+    elif [[ $(command -v nitrogen) ]]; then
+        if [[ ${WALLPAPER_STYLE} == "tile" ]]; then
+            nitrogen --set-tiled "${WALLAPPER_PATH}"
+        else
+            nitrogen --set-zoom "${WALLPAPER_PATH}"
+        fi
     fi
 }
 
-function update_dunst()
+update_dunst()
 {
     if [[ -z ${DUNST_PATH} ]]; then
         printf "Error: Dunst path not set: not reloading dunst\n"
@@ -134,21 +141,7 @@ function update_dunst()
     fi
 }
 
-# Updates 2bwm's config.h with the new system colors
-# Recompiles 2bwm and reloads the window manager
-# Kills all current instances of lemonbar and starts the current bar in the background
-# Globals:
-#   TWOBWM_FOCUS
-#   TWOBWM_UNFOCUS
-#   TWOBWM_FIXED
-#   TWOBWM_UNKILL
-#   TWOBWM_FIXEDUNK
-#   TWOBWM_OUTR
-#   TWOBWM_EMP
-#   TWOBWM_PATH
-# Notes:
-#   Requires xdotool to reload 2bwm
-function reload_2bwm() 
+reload_2bwm() 
 {
     local dir="${TWOBWM_PATH}"
     local file="${TWOBWM_PATH}/config.h"
@@ -169,7 +162,7 @@ function reload_2bwm()
     xdotool key "super+ctrl+r"
 }
 
-function reload_bspwm()
+reload_bspwm()
 {
     if [[ -z ${BSPWM_PATH} ]]; then
         printf "Error: BSPWM_PATH not found, not reloading bspwm\n"
@@ -178,7 +171,7 @@ function reload_bspwm()
     fi
 }
 
-function reload_chef()
+reload_chef()
 {
     if [[ -z ${CHEF_PATH} ]]; then
         printf "Error: CHEF_PATH not found, not reloading windowchef\n"
@@ -187,7 +180,7 @@ function reload_chef()
     fi
 }
 
-function reload_ob() {
+reload_ob() {
     if [[ -z ${OB_PATH} ]]; then
         printf "Error: OB_PATH not found, not reloading openbox\n"
     else
@@ -196,12 +189,7 @@ function reload_ob() {
     fi
 }
 
-# Function that reloads neovim by identify all current sockets and sending
-# remote commands to each instance to reload the $MYVIMRC file
-# NOTE: Requires neovim-remote to function
-# Notes:
-#   Requires neovim-remote to function
-function reload_nvim()
+reload_nvim()
 {
     if [[ ! $(command -v nvr) ]]; then
         printf "Error:: neovim-remote not found\n"
@@ -215,11 +203,7 @@ function reload_nvim()
     fi
 }
 
-# Sends escape codes to all terminals that reflect the colors from the new colorscheme
-# Arguments: 
-#   sequence: escape codes for terminals
-# Notes:
-function reload_terminals() 
+reload_terminals() 
 {
     local seq="${1}"
 
@@ -228,16 +212,7 @@ function reload_terminals()
     done
 }
 
-# Writes a a file specified by ${CACHE_DIR}/x_colors to be sourced by x_resources
-# Contains information about all system colors (foreground, background, cursorcolor, colors 0 - 15)
-# As well as rofi colors and 2bwm colors
-# Globals:
-#   CACHE_DIR
-# Notes:
-#   This file is only useful if it is source in ${HOME}/.Xresources
-#   This can be done with the line: 
-#       #include ".cache/squash/x_colors"
-function write_x() 
+write_x() 
 {
    local x_output=""
    local x_output+="*.foreground:   ${FG}${NEWLINE}"
@@ -245,13 +220,11 @@ function write_x()
    local x_output+="*.cursorColor:  ${FG}${NEWLINE}"
 
    for i in {0..15}; do
-      local x_output+="*.color${i}: ${color_array[${i}]}${NEWLINE}"
+      local x_output+="*.color${i}: ${COLOR_ARRAY[${i}]}${NEWLINE}"
    done
 
    local rofi_output=""
    local rofi_output+="rofi.color-enaled: true${NEWLINE}"
-   #local rofi_output+="rofi.color-window: ${BG}, ${BG}, ${BLK}${NEWLINE}"
-   #local rofi_output+="rofi.color-normal: ${BG}, ${FG}, ${BG}, ${BLK}, ${ACC}${NEWLINE}"
    #                                        bg      fg     bgalt  hlbg     hlfg
    local rofi_output+="rofi.color-window: ${BLK}, ${BLK}, ${BLK}${NEWLINE}"
    local rofi_output+="rofi.color-normal: ${BLK}, ${FG}, ${BLK}, ${BBLK}, ${ACC}${NEWLINE}"
@@ -273,11 +246,7 @@ function write_x()
    printf "${output}" > "${CACHE_DIR}/x_colors"
 }
 
-# Writes a css file that contains all the color information of the current theme
-# to the ${CACHE_DIR}. Can be sourced by any number of applicatons. 
-# Globals:
-#   CACHE_DIR
-function write_css() 
+write_css() 
 {
    local css_output=""
    local css_output+=":root {${NEWLINE}"
@@ -285,35 +254,92 @@ function write_css()
    local css_output+="\t--background: ${BG};${NEWLINE}"
    local css_output+="\t--foreground: ${FG};${NEWLINE}"
    for i in {0..15}; do 
-       local css_output+="\t--color${i}: ${color_array[${i}]};${NEWLINE}"
+       local css_output+="\t--color${i}: ${COLOR_ARRAY[${i}]};${NEWLINE}"
    done
    local css_output+="}"
 
    printf "${css_output}" > "${CACHE_DIR}/colors.css"
 }
 
-# Copies the current bash script to the ${CACHE_DIR} so that it can be sourced by any applications
-# that want access to the variables in the bash script
-# Globals:
-#   CACHE_DIR
-function write_sh() 
+write_sh() 
 {
     rm -f ${CACHE_DIR}/colors
     cp ${THEME_DIR}/${COLOR_SCHEME} ${CACHE_DIR}/colors
 }
 
-# Write all files
-test ${WRITE_ALL} == true && write_x
-test ${WRITE_ALL} == true && write_sh
-test ${WRITE_ALL} == true && write_css
+write_plain()
+{
+    for i in {0..15}; do 
+        local output+="${COLOR_ARRAY[${i}]}${NEWLINE}"
+    done
 
-# Source .Xresources
-xrdb "${HOME}/.Xresources"
+    printf "${output}" > "${CACHE_DIR}/colors.txt"
+}
 
-# Update applications
-test ${RELOAD_WALLPAPER} == true && update_wall
-test ${RELOAD_TERMINALS} == true && update_terminals
-test ${RELOAD_VIM} == true && update_nvim
-test ${RELOAD_BAR} == true && update_bar
-test ${RELOAD_WM} == true && update_wm
-test ${RELOAD_DUNST} == true && update_dunst
+list_files()
+{
+    for file in ${THEME_DIR}/*; do
+        if [[ -f $file ]]; then
+            printf "$(basename "${file}")${NEWLINE}"
+        fi
+    done
+}
+
+get_args()
+{
+    while getopts ":hc:bnwtmdfe:l" opt; do
+        case "$opt" in
+            "h") usage ;;
+            "c") CONFIG_FILE="${OPTARG}" ;;
+            "b") RELOAD_BAR="NO" ;;
+            "n") RELOAD_NVIM="NO" ;;
+            "w") RELOAD_WALLPAPER="NO" ;;
+            "t") RELOAD_TERMINALS="NO" ;;
+            "m") RELOAD_WM="NO" ;;
+            "d") RELOAD_DUNST="NO" ;;
+            "f") WRITE_ALL="NO" ;;
+            "e") EXTERNAL_SCRIPT="${OPTARG}" ;;
+            "l") list_files; exit 1;;
+
+            "?")
+                printf "%s\n" "Invalid option: -$OPTARG" >&2
+                exit 1
+            ;;
+
+            ":")
+                printf "%s\n" "Option -$OPTARG requires an argument." >&2
+                exit 1
+            ;;
+        esac
+    done
+
+    shift $(($OPTIND - 1))
+    COLOR_SCHEME="${1}"
+    [[ ! -f ${THEME_DIR}/${COLOR_SCHEME} ]] && usage
+}
+
+main()
+{
+    get_args "${@}"
+    source "${HOME}/.config/squash/defaults"
+    source "${THEME_DIR}/${COLOR_SCHEME}"
+
+    COLOR_ARRAY=($BLK $RED $GRN $YLW $BLU $MAG $CYN $WHT \
+                 $BBLK $BRED $BGRN $BYLW $BBLU $BMAG $BCYN $BWHT)
+
+    [[ ! "${WRITE_ALL}" == "NO" ]] && write_x
+    [[ ! "${WRITE_ALL}" == "NO" ]] && write_sh
+    [[ ! "${WRITE_ALL}" == "NO" ]] && write_css
+    [[ ! "${WRITE_ALL}" == "NO" ]] && write_plain
+
+    xrdb "${HOME}/.Xresources"
+
+    [[ ! "${RELOAD_WALLPAPER}" == "NO" ]] && update_wall 
+    [[ ! "${RELOAD_TERMINALS}" == "NO" ]] && update_terminals
+    [[ ! "${RELOAD_NVIM}" == "NO" ]] && update_nvim
+    [[ ! "${RELOAD_BAR}" == "NO" ]] && update_bar
+    [[ ! "${RELOAD_WM}" == "NO" ]] && update_wm
+    [[ ! "${RELOAD_DUNST}" == "NO" ]] && update_dunst
+}
+
+main "${@}"
